name: Simple Upload Test

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload test file
      run: |
        mkdir -p bin
        touch bin/test.apk
        ls bin/
      
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: test-apk
        path: bin/test.apk
