- name: Check if APK exists
  run: |
    echo "Mengecek apakah file APK sudah ada di folder bin/"
    ls -la bin/
    if [ -f "bin/YTDownloaderApp-debug.apk" ]; then
      echo "APK ditemukan, melanjutkan ke upload."
    else
      echo "APK tidak ditemukan, build gagal!"
      exit 1
    fi
